# Generated by Django 5.0.6 on 2024-06-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsletterModel',
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='newslettermodel',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='newslettermodel',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
